### ISSUE TITLE
EFC: multiple energy sources

### ISSUE THREAD

**Issue by pandafulmanda** [Connexions/simulations#280] opened 2015-06-11 15:47 UTC
![screen shot 2015-06-11 at 10 45 40 am](https://cloud.githubusercontent.com/assets/2483873/8111367/0720572c-1027-11e5-88de-84459cc02a18.png)

![screen shot 2015-06-11 at 10 48 00 am](https://cloud.githubusercontent.com/assets/2483873/8111423/5a96b568-1027-11e5-8487-ea3c22f35cf1.png)

Changed energy types, etc. serveral times and then it looks like this

hard to consistently reproduce, so probably minor?

**Comment by pwolfert** [comment] 2015-06-18 18:02
Duplicate of https://github.com/Connexions/simulations/issues/45

**Closed** 2016-05-23 21:50 UTC
Labels: bug, duplicate
