### ISSUE TITLE
Energy Forms - Sim needs to scroll on small screens

### ISSUE THREAD

**Issue by edwoodward** [Connexions/simulations#38] opened 2015-01-06 17:52 UTC
I tested the sim on the Nexus 7 and my Nvidia Shield which is an 8 inch tablet.  The problem is that you cannot scroll to get to some of the functinality.  What I could get to worked, but it was very limited. I was able to scroll earlier sims.

**Comment by pwolfert** [comment] 2015-01-08 17:36
I just tried it on a touch screen device, and I think the problem here is that the whole simulation viewport is a canvas, and PIXI is capturing the drag events for its own purposes.  I'll look into this and see what I can find.

**Comment by pwolfert** [comment] 2015-01-08 17:41
My plan for when I get around to it:

I found [here](https://github.com/GoodBoyDigital/pixi.js/issues/814) that the following line will allow scrolling on mobile:
`PIXI.AUTO_PREVENT_DEFAULT = false`
The problem is that if we then try to drag elements, it moves the elements AND scrolls.  So my plan is to find a way to disable scrolling while a drag event is happening, and that should fix it.

**Comment by edwoodward** [comment] 2015-01-08 18:12
This is low priority since we are not supporting touch devices 
initially.  I was more documenting the problem than expecting an 
immediate fix.

**Comment by brittweinstein** [comment] 2018-09-26 19:33
Closing due to issue age.

**Closed by brittweinstein** 2018-09-26 19:33 UTC
Labels: bug, low priority
