### ISSUE TITLE
Energy Formas and Changes - model freaks out

### ISSUE THREAD

**Issue by edwoodward** [Connexions/simulations#331] opened 2015-09-15 15:31 UTC
The PhET team was looking over our work and noticed a problem with this sim.

1. Open the sim
2. Go to the Energy Systems tab
3. Turn on the faucet so water is flowing
4. Check the "Show Energy" button
5. Press the solar panel button
6. The model will then go wild... 

Screenshot
![screenshot from 2015-09-15 10 29 03](https://cloud.githubusercontent.com/assets/1394695/9881246/b224db4e-5b94-11e5-84dc-456c7be9ceef.png)

**Comment by pwolfert** [comment] 2016-05-22 02:44
Duplicate of #45

**Closed by pwolfert** 2016-05-22 02:44 UTC
Labels: bug
